### ISSUE TITLE
script.js

### ISSUE THREAD

**Issue by facuquilmes123** [xbaysal11/insta-info#1]
Is working script.js?
i just try    <script src="script.js"></script> chage for    <script src="./script.js"></script> but not work

**Comment by xbaysal11** [comment]
> Is working script.js?
> i just try <script src="script.js"></script> chage for <script src="./script.js"></script> but not work

Hi. I don't know why it doesn't work for you, but it still works for me.
Write about the error in more detail with screenshots.

**Comment by facuquilmes123** [comment]
> > Is working script.js?
> > i just try <script src="script.js"></script> chage for <script src="./script.js"></script> but not work
> 
> Hi. I don't know why it doesn't work for you, but it still works for me.
> Write about the error in more detail with screenshots.

Hello, thank you very much for responding so quickly. I really admire your work.
I was able to solve it, it was a problem of my hosting. I'm a newbie and I'm learning a lot from your code.

I would love for you to help me organize the JSON response.
For example, filter the results to only followers or order the output in a table.

I am very grateful for your help.

Keep it up, you help us many beginners

**Comment by xbaysal11** [comment]
> > > Is working script.js?
> > > i just try <script src="script.js"></script> chage for <script src="./script.js"></script> but not work
> > 
> > 
> > Hi. I don't know why it doesn't work for you, but it still works for me.
> > Write about the error in more detail with screenshots.
> 
> Hello, thank you very much for responding so quickly. I really admire your work.
> I was able to solve it, it was a problem of my hosting. I'm a newbie and I'm learning a lot from your code.
> 
> I would love for you to help me organize the JSON response.
> For example, filter the results to only followers or order the output in a table.
> 
> I am very grateful for your help.
> 
> Keep it up, you help us many beginners

All right, I'll do it as quickly as possible. Wait for updates.
Thank you for your feedback and suggestions.
Good luck in your endeavors.
